"""Agent and Tool Calling evaluators (Tool Selection, Schema Compliance, Abstention)."""

import json
from typing import Any, Dict, List, Optional, Union
from microevals_core.evaluators.base import BaseEvaluator, EvalResult
from microevals_core.evaluators.rule import RuleEvaluator


class AgentEvaluator(BaseEvaluator):
    """Evaluates Tool/Function calling capabilities and Agent trajectories."""

    def __init__(self):
        self._rule_evaluator = RuleEvaluator()

    async def evaluate(
        self,
        output_text: str,
        prompt: str = "",
        ground_truth: Optional[str] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> EvalResult:
        context = context or {}
        eval_type = context.get("eval_type", "tool_selection")
        called_tools = context.get("called_tools", [])

        if eval_type == "tool_selection":
            expected = context.get("expected_tools", [])
            forbidden = context.get("forbidden_tools", [])
            return self.evaluate_tool_selection(called_tools, expected, forbidden)
        elif eval_type == "argument_schema":
            tool_name = context.get("tool_name", "")
            arguments = context.get("arguments", "{}")
            schema = context.get("schema", {})
            return self.evaluate_argument_schema(tool_name, arguments, schema)
        elif eval_type == "abstention":
            return self.evaluate_abstention(called_tools)
        else:
            return EvalResult(
                evaluator_name="agent_eval",
                passed=False,
                score=0.0,
                reason=f"Unknown agent evaluation type: {eval_type}",
            )

    def evaluate_tool_selection(
        self,
        called_tools: List[Union[Dict[str, Any], Any]],
        expected_tools: Optional[List[str]] = None,
        forbidden_tools: Optional[List[str]] = None,
    ) -> EvalResult:
        """Verify whether expected tools were invoked and forbidden tools avoided."""
        expected_set = set(expected_tools or [])
        forbidden_set = set(forbidden_tools or [])

        actual_names = set()
        for t in called_tools:
            name = t.get("name") if isinstance(t, dict) else getattr(t, "name", "")
            if name:
                actual_names.add(name)

        # Check missing expected tools
        missing = expected_set - actual_names
        # Check forbidden tools that were called
        violations = forbidden_set.intersection(actual_names)

        passed = len(missing) == 0 and len(violations) == 0

        # Score calculation: proportion of expected tools called
        if expected_set:
            score = len(expected_set - missing) / len(expected_set)
        else:
            score = 1.0 if passed else 0.0

        if violations:
            score = 0.0

        reasons = []
        if missing:
            reasons.append(f"Missing expected tools: {list(missing)}")
        if violations:
            reasons.append(f"Forbidden tools called: {list(violations)}")
        if not reasons:
            reasons.append(f"Tools selection passed (called: {list(actual_names)})")

        return EvalResult(
            evaluator_name="agent_tool_selection",
            passed=passed,
            score=round(score, 2),
            reason="; ".join(reasons),
            details={
                "called_tools": list(actual_names),
                "expected_tools": list(expected_set),
                "forbidden_tools": list(forbidden_set),
            },
        )

    def evaluate_argument_schema(
        self,
        tool_name: str,
        arguments_json: Union[str, Dict[str, Any]],
        schema: Dict[str, Any],
    ) -> EvalResult:
        """Verify that arguments generated by the model conform to the tool's JSON Schema."""
        arg_str = json.dumps(arguments_json) if isinstance(arguments_json, dict) else str(arguments_json)
        res = self._rule_evaluator.evaluate_json_schema(arg_str, schema)

        return EvalResult(
            evaluator_name=f"agent_arg_schema_{tool_name}",
            passed=res.passed,
            score=res.score,
            reason=f"Tool '{tool_name}' argument schema: {res.reason}",
            details=res.details,
        )

    def evaluate_abstention(self, called_tools: List[Any]) -> EvalResult:
        """Anti-hallucination test: asserts that NO tools were called for non-tool queries."""
        has_tools = len(called_tools) > 0
        passed = not has_tools
        return EvalResult(
            evaluator_name="agent_abstention",
            passed=passed,
            score=1.0 if passed else 0.0,
            reason="Correctly abstained from calling tools"
            if passed
            else f"Hallucinated {len(called_tools)} tool call(s) when none were expected",
            details={"called_tools_count": len(called_tools)},
        )
